[pytest]
pythonpath = .
addopts = 
    --html=results/pytest/report.html
    --self-contained-html
    --junit-xml=results/pytest/junit.xml
    -v --reruns 3 --reruns-delay 5
log_cli = true
log_cli_level = INFO
log_file = results/pytest/pytest.log
log_file_level = DEBUG